package Enums;

public enum T_Depto {
    INVESTIGACION,
    NARCOTICOS,
    COMUNICACIONES,
    TRANSITO,
    SEGURIDAD,
    CIENTIFICA,
    FORMACION,
    LIMPIEZA,
    SECRETARIA,
    ADMINISTRACION,
    RECURSOS_HUMANOS;
}
